### ISSUE TITLE
How can I make back button on Android ActionBar?

### ISSUE THREAD

**Issue by dlehdanakf** [jineshshah36/react-native-nav#18]
Hi,
I want to make a button on the left of page title so that user can go back to prev page.
```
<NavBar>
    <NavButton></NavButton>
    <NavTitle>{"HI"}</NavTitle>
</NavBar>
````
This code will position the page title to the right side of monitor.
But I want to place page title right by right of button.

How can I do that?

**Comment by jineshshah36** [comment]
You need to style the `NavBar` component to have a different `justifyContent`. Most likely, you want to use `flex-start` rather than `space-between`

**Comment by jineshshah36** [comment]
closing this due to no response.
