### ISSUE TITLE
Nav title not centered

### ISSUE THREAD

**Issue by tonyxiao** [jineshshah36/react-native-nav#7]
When buttons are of different width, title is no longer centered. See

``` jsx
        <NavBar>
          <NavButton onPress={() => alert('hi')}>
            <NavButtonText>
              Button
            </NavButtonText>
          </NavButton>
          <NavTitle>Title</NavTitle>
          <NavButton>
          <NavButtonText>
          B
          </NavButtonText>
          </NavButton>
        </NavBar>
```

![image](https://cloud.githubusercontent.com/assets/696842/15101455/a4cc2c84-1545-11e6-98be-e40ab7a64d20.png)

Also, what If I just want a single title without any buttons?

``` jsx
        <NavBar>
          <NavTitle>Title</NavTitle>
        </NavBar>
```

I get this instead of the desired center behavior

![image](https://cloud.githubusercontent.com/assets/696842/15101463/d7766c94-1545-11e6-8f4e-d4e2f2af6984.png)

**Comment by jineshshah36** [comment]
You will need to edit the default styles in both situations to get it to work. You could put each button in its own `NavGroup` and set an equal width for both `NavGroups`. For the second example, just set `justifyContent: 'center'`

**Comment by jineshshah36** [comment]
No response from OP
